[build]
  command = "npx vite build --config vite.vercel.config.ts"
  publish = "dist"
  functions = "netlify/function"

[[redirects]]
  from = "/.netlify/functions/proxy"
  to = "/.netlify/function/proxy"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
